# Generated by Django 4.2.2 on 2023-06-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CounselorSchedule', '0002_timeslot_is_booked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name_plural': 'Counselor Schedules'},
        ),
    ]
