# Generated by Django 4.2.2 on 2023-06-09 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0003_alter_student_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='Home.counselor')),
            ],
        ),
    ]
