# Generated by Django 4.2.2 on 2023-06-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counselorinfosection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Infos'},
        ),
    ]
