# Generated by Django 4.2.2 on 2023-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_user_is_counselor_user_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_profile',
            field=models.ImageField(default='images/default.png', upload_to='student_profiles'),
        ),
    ]
