# Generated by Django 4.2.2 on 2023-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_student_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='counselor_profile',
            field=models.ImageField(default='default.png', null=True, upload_to='counselor_profiles'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_profile',
            field=models.ImageField(default='default.png', upload_to='student_profiles'),
        ),
    ]
