# Generated by Django 4.2.2 on 2023-06-10 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_counselor_counselor_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='counselor_profile',
            field=models.ImageField(default='default.png', upload_to='counselor_profiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='qualification',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_profile',
            field=models.ImageField(default='default.png', upload_to='student_profiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
