# Generated by Django 4.1.7 on 2023-08-03 05:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_counselor_counselor_profile_and_more'),
        ('StudentDiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('diary', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='Home.student')),
            ],
            options={
                'verbose_name_plural': 'Diaries',
            },
        ),
        migrations.DeleteModel(
            name='DiaryEntry',
        ),
    ]
