# Generated by Django 4.1.7 on 2023-08-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('youtube_video_id', models.CharField(max_length=20)),
                ('compliments', models.TextField()),
            ],
        ),
    ]
