# Generated by Django 4.1.7 on 2023-08-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserExercise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
